#!/bin/bash

if [ -z "$1" ]; then
    echo "You must provide a driver name as an argument. Eg. ./run_driver Player (for PlayerDriver.cpp)"
    exit 1
fi

CPP_STD="-std=c++14"
CPP_FILES="Cards.cpp Player.cpp Map.cpp MapLoader.cpp util/*.cpp $1Driver.cpp"

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    COMPILER="g++" 
elif [[ "$OSTYPE" == "darwin"* ]]; then
    COMPILER="clang++"
fi

$COMPILER -Wall $CPP_STD $CPP_FILES

./a.out